### PR TITLE
Wormbase allowed species list update for 106

### PR DESCRIPTION
**Pull request by digrigor**
Adding new worm genomes submitted by Wormbase.

## Description

_Describe the problem you're addressing here._

**Related JIRA tickets:**
- ENSCOMPARASW-XXXX

## Overview of changes
_Give details of what changes were required to solve the problem. Break into sections if applicable._

#### Change 1
- _detail 1.1_

#### Change 2
- _detail 2.1_

## Testing
_How was this tested? Have new unit tests been included?_

## Notes
_Optional extra information._

### CODE REVIEW

**Review by ipilizota — APPROVED** [review]
Adding 4 more species on top of those in PR #321. Still within the allowed limits for 1) number of changes in the species list per release, and 2) max total number of genomes in the division.

**Comment by ipilizota** [comment]
I think Travis is failing for reasons unrelated to this PR.

**Comment by ipilizota** [comment]
Hi @digrigor :) 
Could you please rebase your branch from `master` because Vasily has already committed and merged some Metazoa changes to our `master` branch - and those changes are not reflected in the `allowed_species.json` you started with.
I am really sorry to keep bugging you with something that you probably thought would go smoother.

**Comment by digrigor** [comment]
No worries @ipilizota! Sure, i will do now :)

**Pull request closed without merging**
