### PR TITLE
I want to update dnafrag name from varchar(40) to varchar(255)

### PR DESCRIPTION
**Pull request by gnaamati**
This will also be consistent with seq_region name in core

### CODE REVIEW

**Comment by muffato** [comment]
I'm OK with the patch but I already have a number of patches lined up for e88 (several in the dnafrag table). Let me see what's the best strategy regarding naming the patches

**Comment by gnaamati** [comment]
Thanks Matthieu. It might be easier to add it to one of the existing patches, especially if they are for the dnafrag table. What you think is best.

**Comment by gnaamati** [comment]
Hi Matthieu, I think the name of the patch file I created should be patch_87_88_b.sql and not patch_87_88.b.sql. If you want I can commit again or you can add it to an existing patch like discussed above,

**Comment by muffato** [comment]
Hi Guy,
I've pushed the _a patch (version 87 -> 88). Can you rebase your commits onto master (sql/table.sql has changed near the line you've edited)

**Comment by gnaamati** [comment]
Hi Matthieu, do I also need to do a new commit for patch_87_88_b.sql? 
Thanks
Guy

**Comment by gnaamati** [comment]
Hi Matthieu,

I have created a new pull request for these two updates using a new updated fork: 
https://github.com/Ensembl/ensembl-compara/pull/59

Thanks
Guy

**Comment by muffato** [comment]
Superseded by #59

**Pull request closed without merging**
