### PR TITLE
Add initial Fungi config and pipeconfig files

### PR DESCRIPTION
**Pull request by twalsh-ebi**
## Description

Compara is taking on Fungi in Ensembl 108.

**Related JIRA tickets:**
- ENSCOMPARASW-5023
- ENSCOMPARASW-5024
- ENSCOMPARASW-5421

## Overview of changes
Fungi config and pipeconfig files have been prepared
following the approach used in preparing Protists.

#### Fungi config files
- `allowed_species.json`: checked and formatted species list.
- `jira_recurrent_tickets.json`: added general post-e105 updates and fungi-specific server information.
- `mlss_conf.xml`: changed protein-tree collection to "default", added "default" collection element.
- `production_reg_conf.pl`: Placeholder file with expected database information.
  This will be updated with more concrete information as needed during production setup.

#### Fungi pipeconfig files

- PipeConfig files have been added with protein-trees and LASTZ alignments in mind.
- No LASTZ alignments are planned for e108, but these will be useful in a future release.
- No dN/dS analysis is needed, so this has been switched off.
- Some pipeline configuration options are expected
  to be updated during production, as needed.

## Testing
N/A

## Notes

This is a draft pull request, so all constructive feedback is welcome.

### CODE REVIEW

**Review by CristiGuijarro — COMMENTED** [review]
I wasn't sure whether to review this because it is a draft. It looks fine to me, the only suggestion I would make would be to save the `production_reg_conf.pl` changes for during the release on the `release/108` branch. There is also a potential conflict for the `jira_recurrent_tickets.json` with PR: https://github.com/Ensembl/ensembl-compara/pull/428

**Comment by ipilizota** [comment]
@CristiGuijarro, @twalsh-ebi Shall we maybe merge [PR#428](https://github.com/Ensembl/ensembl-compara/pull/428) first, then Tom can rebase his branch and resolve potential conflicts?

**Comment by twalsh-ebi** [comment]
> I still think `production_reg_conf.pl` changes should be saved for after branching to `release/108` - but I also don't think it should block the PR, so I will leave it up to you 👍

The changes that have been left in place were modelled on [the most recent comparable PR](https://github.com/Ensembl/ensembl-compara/pull/378/files), which was also submitted before branching to the relevant release.

**Review by ipilizota — APPROVED** [review]

**Comment by CristiGuijarro** [comment]
> > I still think `production_reg_conf.pl` changes should be saved for after branching to `release/108` - but I also don't think it should block the PR, so I will leave it up to you +1
> 
> The changes that have been left in place were modelled on [the most recent comparable PR](https://github.com/Ensembl/ensembl-compara/pull/378/files), which was also submitted before branching to the relevant release.

This PR was  the initial commit of the file required for branching. `fungi/production_reg_conf.pl` already has this initial commit in `main`, the reg_conf.pl was then further adapted for `release/107`. The idea is to preserve the commits as they are used for the branches, before branching the file should reflect the history of usage, and should be as it was for the last release in which it was used. Then when it comes to `release/108` it will be adapted for `release/108` use and changed here, then later merged into `main` from `release/108` - I am not sure how well I am explaining this... :sweat_smile:

**Comment by twalsh-ebi** [comment]
> > > I still think `production_reg_conf.pl` changes should be saved for after branching to `release/108` - but I also don't think it should block the PR, so I will leave it up to you +1
> > 
> > 
> > The changes that have been left in place were modelled on [the most recent comparable PR](https://github.com/Ensembl/ensembl-compara/pull/378/files), which was also submitted before branching to the relevant release.
> 
> This PR was the initial commit of the file required for branching. `fungi/production_reg_conf.pl` already has this initial commit in `main`, the reg_conf.pl was then further adapted for `release/107`. The idea is to preserve the commits as they are used for the branches, before branching the file should reflect the history of usage, and should be as it was for the last release in which it was used. Then when it comes to `release/108` it will be adapted for `release/108` use and changed here, then later merged into `main` from `release/108` - I am not sure how well I am explaining this... 😅

This is how the `protists/production_reg_conf.pl` server config was in PR #378: 
https://github.com/Ensembl/ensembl-compara/blob/26642698978e1994063ed604046e770891801430/conf/protists/production_reg_conf.pl#L94-L100
If you don't mind @CristiGuijarro, I'm just going to merge this PR now and get on with it.

**Pull request merged**
