### PR TITLE
Dev/citest

### PR DESCRIPTION
**Pull request by dthybert**
Taking into acount of push request feedbacks and implementation of python convention

ci_test.py: comments have been added and the PEP8 coding convention is followed
           pylint gave a score of 10. I have also renamed the file to follow pep8 convention
citest.py: comments have been added and the PEP8 coding convention is followed
           pylint gave a score of 10.
tabletest.py: comments have been added and the PEP8 coding convention is followed,
             I also corrrected a bug after unittest tests
test.py: comments have been added and the PEP8 coding convention is followed
         pylint gave a score of 10.

### CODE REVIEW

**Comment by carlacummins** [comment]
Travis is still failing because of missing licences in `scripts/citest/ci_test.py` (previous PR comment: https://github.com/Ensembl/ensembl-compara/pull/157#discussion_r347890468)

Also, you should have continued to use the previous pull request instead of creating a new one. When you push commits to the same branch, the PR is updated, so there is no need to start again. Also, github is smart and will automatically tell us which of my comments you've addressed and which ones you haven't - now I kind of have to start the review from scratch... 😞

**Comment by dthybert** [comment]
Sorry about this. I though the changes of integrating all the pep8 and documentation would have bee too important and easier to start form scratch. I will have learnt for the next time...

**Comment by dthybert** [comment]
What makes the licence failing on travis (what are the rules)? because the licence text is in the file...

**Comment by muffato** [comment]
I could close this PR and reopen #157 (sine they're the same anyway). @carlacummins . You should be able to carry one

**Pull request closed without merging**
