### PR TITLE
Vega59 fixes.

### PR DESCRIPTION
**Pull request by ens-ds23**
Including a modification to PrepareSpeciesSetsMLSS to allow master database with SS and MLSS missing.

Feel free to rename and rearrange the param, etc, if needed.

### CODE REVIEW

**Comment by muffato** [comment]
OK for the modifications in the config files. It is in fact similar in spirit to the edits that are made to the PairAligner. I'll try to make something generic in a base class so that you only have to override analyses_to_remove() and tweak_analyses()

I still have to look at PrepareSpeciesSetsMLSS. Nothing wrong in principle: I just want to think carefully of the use case

**Comment by muffato** [comment]
What do you have in the master db ? only the genome_dbs and their dnafrags ? and you create SS/MLSS for the alignments but not for the protein trees ?

**Comment by muffato** [comment]
No: according to the config, the master db is also missing the dnafrags. So you only need the master db to define a list of species to run the pipeline on (list of genome_dbs, global SS and global MLSS)

**Comment by ens-ds23** [comment]
Hi Matthieu, The only thing I was aware of was the master MLSS etc, as you suggest. I'm not positive about that, but it would be great not to have to use a master db as it's an extra step for us to prepare it. We were manually adding MLSS/SS for new species but it got out of sync at some point and neither us nor the old code noticed, so it was adding MLSS/SS for new species each time. The new code is stricter, though. Our handling of master databases is clunky, so feel free to advise.

**Comment by muffato** [comment]
Hi Dan,
The pipeline already has a master-free mode but there is no way of limiting the species set to build trees on: it takes all the species (core dbs of a given version) found on the configured servers. Would it help ?

If not, what about having a Registry file with the list of the core databases you want to include ? (and no master db any more)

Matthieu

**Pull request merged**
