### PR TITLE
s/rh6/rh7/

### PR DESCRIPTION
**Pull request by dbolser-ebi**
Hey! That was easy!

### CODE REVIEW

**Comment by mateuspatricio** [comment]
Looks good to me.

**Comment by dbolser-ebi** [comment]
Please note I just pushed another commit.. (probably bad practice!)

**Comment by dbolser-ebi** [comment]
I don't know if EG/DumpMultiAlign_conf.pm is actually used by anyone... any reason we have an EG specific version of this this pipeline?

**Comment by muffato** [comment]
It is used by Production. It's a variant of the default pipeline. It dumps _everything_ regardless of when the data were created, and if there is already a dump.
We run the basic pipeline "manually", i.e. for each new mlss_id

**Comment by dbolser-ebi** [comment]
Thanks.
​

**Pull request merged**
