### PR TITLE
plant updates for 107

### PR DESCRIPTION
**Pull request by gnaamati**
## Description

Plants tree and allowed species for 107

### CODE REVIEW

**Comment by dthybert** [comment]
you also need to update this file. https://github.com/Ensembl/ensembl-compara/blob/release/106/conf/plants/allowed_species.json

**Review by dthybert — CHANGES_REQUESTED** [review]
you need to update this file as well https://github.com/Ensembl/ensembl-compara/blob/release/106/conf/plants/allowed_species.json

**Comment by gnaamati** [comment]
Thanks @dthybert I will do this tomorrow after I discuss with Sarah

**Comment by gnaamati** [comment]
I've added the allowed species for 107

**Comment by ipilizota** [comment]
Hi @gnaamati 🙂 
Due to frozen release, there are some limits in the number of species. The latest info I have is that the overall number of plant species should be 100 max, with max 10 species with new or updated assembly per release. Polyploid species are counted based on the number of their subgenomes, so e.g. wheat counts as 3 genomes.
Please correct me if there is more recent info on that or if the inclusion of proposed species has been negotiated separately.

**Review by ipilizota — CHANGES_REQUESTED** [review]
Hi @gnaamati 🙂
Due to frozen release, there are some limits in the number of species. The latest info I have is that the overall number of plant species should be 100 max, with max 10 species with new or updated assembly per release. Polyploid species are counted based on the number of their subgenomes, so e.g. wheat counts as 3 genomes.
Please correct me if there is more recent info on that or if the inclusion of proposed species has been negotiated separately.

**Comment by ipilizota** [comment]
@gnaamati I apologise. I updated myself in the meantime and will get back to reviewing the PR with the info I got. In the meantime, please don't make any changes 😉

**Review by ipilizota — APPROVED** [review]

**Review by dthybert — APPROVED** [review]

**Pull request merged**
