### PR TITLE
Centralise repository's test data

### PR DESCRIPTION
**Pull request by JAlvarezJarreta**
## Description

Moved all test files (both databases and flatfiles from Perl and Python) into a single central place in `src/test_data`. For Perl, all folders have been symlinked keeping the existing structure. In Python I have opted to change the path in the code instead (since it is in a single place, whilst I fear it is not the same for Perl).

## Testing
I have run both Perl and Python unit tests and all have passed in Codon.

### CODE REVIEW

**Review by ipilizota — APPROVED** [review]

**Review by twalsh-ebi — APPROVED** [review]

**Comment by JAlvarezJarreta** [comment]
I can confirm the patching script works as it was before :fireworks:

**Review by thiagogenez — APPROVED** [review]
Looks good to me.

**Comment by thiagogenez** [comment]
By the way, is it possible to make `mypy` to suppress that error?

**Comment by JAlvarezJarreta** [comment]
> By the way, is it possible to make `mypy` to suppress that error?

On it on the `main` branch :+1:

**Pull request merged**
