### PR TITLE
Metazoa allowed species list update for 106

### PR DESCRIPTION
**Pull request by vsitnik**
## Description

Metazoa allowed species list update for 106

**Related JIRA tickets:**
https://www.ebi.ac.uk/panda/jira/browse/ENSINT-905

## Overview of changes
Modifying allowed species json for compara

#### Change 1
1 old cell line deleted
#### Change 2
2 new species added
#### Change 3
1 species candidate added
#### Change 4
2 more species candidate added

## Testing
```
cat allowed_species.json |
  python -m json.tool |
  diff - allowed_species.json > /dev/null
```

### CODE REVIEW

**Comment by vsitnik** [comment]
ready to be merged.

tested with
```
cat allowed_species.json |
  python -m json.tool |
  diff - allowed_species.json > /dev/null 
```

**Comment by CristiGuijarro** [comment]
:information_source: Travis is failing for reasons unrelated to this PR - as long as the PR meets the specs, it should be safe to merge :+1:

**Comment by ipilizota** [comment]
Adding 5, removing 1 -> within the allowed limits for changes in species list and for the max total number of genomes in the division

**Review by ipilizota — APPROVED** [review]
Adding 5, removing 1 -> within the allowed limits for 1) number of changes in the species list, and 2) max total number of genomes in the division

**Comment by JAlvarezJarreta** [comment]
I think we need to clarify in the SOP that both @dthybert and the division's relco need to approve the PR before it is merged.

**Pull request merged**
